name: Demo Continous Integration for Batch2
'on':
  push:
    branches:
      - master
      - stage1
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v3
      - name: Download and Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin
          continue-on-error: true
      - name: Download and Setup Maven
        uses: stcarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
      - name: Build using Maven
        run: mvn clean install
        
  test:
    needs: build
    runs-on: '${{ needs.build.outputs.runs-on}}'
    steps:
      - name: Run Test
        run: mvn clean test "-Dcucumber.filter.tags=@smoke"
    env:
      DISPLAY: 19
      CUCUMBER_PUBLISH_TOKEN: 5a34f351-332e-447c-9238-ba3550c3f89e
      continue-on-error: true
